# Site settings
title: title
description: 花有重开日 任务在少年
#baseurl: "/blog" 
url: "https://github.com/sjcnh"

# User settings
username: 诗酒趁年华
user_description: I'll see you when I see you.
user_title: Software Developer
email: anon@anon.com
twitter_username: 
github_username:  sjcnh
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
