# Site settings
title: Ê«¾Æ³ÃÄê»ª
description: time waits for no one
#baseurl: "/blog" 
url: "https://github.com/sjcnh"

# User settings
username: sjcnh
user_description: I'll see you when I see you.
user_title: Software Developer
email: anon@anon.com
twitter_username: 
github_username:  sjcnh
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
